services:
  db:
    image: 'postgres:latest'
    env_file: .env
    expose:
      - '5432'
    volumes:
      - ProjectSourceCode:/var/lib/postgresql/data
      - ./src/init_data:/docker-entrypoint-initdb.d
  web:
    image: node:lts
    #If user: 'node' does not work try either leaving the user blank or using the following line instead
    #user: 'root'
    #user: 'node'
    working_dir: /ProjectSourceCode
    env_file: .env
    environment:
      - NODE_ENV=development
    depends_on:
      - db
    ports:
      - '3000:3000'
    volumes:
      - ./:/ProjectSourceCode
    command: 'npm run testandrun'
volumes:
  ProjectSourceCode: